@startuml "goods_relations"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Rel(goods_service, goods_db, "Stores goods information")
Rel(goods_service, goods_search, "Indexes goods")

@enduml
